language: cpp
sudo: enabled
env:
  global:
    - secure: "pI5jjosFPpFUU7u9pbWPlIo27PXh/A6L0n0HmhXssLllQ3lOGJpcWuYNN4EXdtk+kS88o2HjZHZyJwsNn1NKZ5X2wr7nGchNB1spPI80bCsFETRL+u8GqGy9OFTaAHvBjqssW9A0BqTcUjrJoPiclcHgIduC8adfq5w+nRY77dePCn+S0utiw8tdowZAUANTNllfBrp+FVF6RQ0jpLy2eCdV0SabGW6dmxAculmmEvPsjGajc5Hktk4siNwSuNNLuJBX8VKoXshPhZuw+jsxq++R5gX5ixGDxz1uUO+0KkZooPLv5SdeQEdpbkwAWqH/ehv0YLTlQuVAAigaGRzilKSossr2tgVY9/juCHsjYQhUD+SxIDbOTMJ+XiFmn8qh/vwhckwScTFfYGnNvpREq7E4j9A6WSUurO5b27Xl4bYa40ZBSO0qdsvP8s3Z15+Fe8e3ZjNyfugRQF9FujUreHzaCLmEGczGjPKB/+A0y7LxMdtGVt7MuCGuBIdMZQYdVDNKoQpZizEk05LDQIy36oIZ9L5iQP0VSXiwz0A5Hz/Ai7a0A7JYuLVkIhUmPo9qtZjrugqa/Ia9TIXkmOBTjX82tXGTATfiLvWZI+aKtVdjQlCDc57HfYa1p30KXBOZSjhaPWfYRbmokqfsNBRmep+JetWYYfb3Bw9z+FphfPA="
branches:
  only:
  - master

# http://openal-soft.org/openal-binaries/
# https://www.libsdl.org/release/
# https://www.libsdl.org/projects/SDL_image/release/
# https://www.libsdl.org/projects/SDL_ttf/release/
# http://downloads.xiph.org/releases/ogg/
# http://downloads.xiph.org/releases/vorbis/

before_install:
  - cat /proc/cpuinfo
  - pushd /tmp
  - export CC=
  - export CXX=
  - echo Creating symlink from /usr/local/cross-tools/ to /usr/
  - sudo ln -s /usr/ /usr/local/cross-tools
  - echo Creating symlink from /usr/local/i686-w64-mingw32 to /usr/i686-w64-mingw32
  - sudo ln -s /usr/i686-w64-mingw32 /usr/local/i686-w64-mingw32
  - echo Creating symlink from /usr/local/x86_64-w64-mingw32 to /usr/x86_64-w64-mingw32
  - sudo ln -s /usr/x86_64-w64-mingw32 /usr/local/x86_64-w64-mingw32
  - sudo apt-get update
  - sudo apt-get install -y mingw-w64 autoconf m4
  - echo Downloading and installing OpenAL
  - cd /tmp
  - wget http://openal-soft.org/openal-binaries/openal-soft-1.18.2-bin.zip
  - unzip openal-soft-*-bin.zip
  - sudo mkdir /usr/i686-w64-mingw32/bin/ || true
  - sudo mkdir /usr/i686-w64-mingw32/lib/ || true
  - sudo mkdir /usr/x86_64-w64-mingw32/bin/ || true
  - sudo mkdir /usr/x86_64-w64-mingw32/lib/ || true
  - sudo cp -Rfpv openal-soft-*-bin/bin/Win32/* /usr/i686-w64-mingw32/bin/
  - sudo cp -Rfpv openal-soft-*-bin/libs/Win32/* /usr/i686-w64-mingw32/lib/
  - sudo cp -Rfpv openal-soft-*-bin/include /usr/i686-w64-mingw32/
  - sudo cp -Rfpv openal-soft-*-bin/bin/Win64/* /usr/x86_64-w64-mingw32/bin/
  - sudo cp -Rfpv openal-soft-*-bin/libs/Win64/* /usr/x86_64-w64-mingw32/lib/
  - sudo cp -Rfpv openal-soft-*-bin/include /usr/x86_64-w64-mingw32/
  - echo Downloading and installing SDL2
  - cd /tmp
  - wget https://www.libsdl.org/release/SDL2-devel-2.0.8-mingw.tar.gz
  - tar xvf SDL2-devel-*-mingw.tar.gz
  - cd SDL2-*/
  - sudo make cross
  - echo Downloading and installing SDL2_image
  - cd /tmp
  - wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.3-mingw.tar.gz
  - tar xvf SDL2_image-*.tar.gz
  - cd SDL2_image-*/
  - sudo make cross
  - echo Downloading and installing SDL2_ttf
  - cd /tmp
  - wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.14-mingw.tar.gz
  - tar xvf SDL2_ttf-*.tar.gz
  - cd SDL2_ttf-*/
  - sudo make cross
  - echo Downloading and installing SDL2_net
  - cd /tmp
  - wget https://www.libsdl.org/projects/SDL_net/release/SDL2_net-devel-2.0.1-mingw.tar.gz
  - tar xvf SDL2_net-*.tar.gz
  - cd SDL2_net-*/
  - sudo make cross
  - echo Downloading and installing Ogg which is a dependency of Vorbis
  - cd /tmp
  - wget http://downloads.xiph.org/releases/ogg/libogg-1.3.3.tar.gz
  - tar xvf libogg-*.tar.gz
  - cd libogg-*/
  - ./configure --target=i686-w64-mingw32   --host=i686-w64-mingw32 --build=i686-linux --prefix=/usr/i686-w64-mingw32
  - echo Compiling Ogg for i686
  - make -j2
  - sudo make install
  - make distclean
  - ./configure --target=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --build=x86_64-linux --prefix=/usr/x86_64-w64-mingw32
  - echo Compiling Ogg for x86_64
  - make -j2
  - sudo make install
  - echo Downloading and installing Vorbis
  - cd /tmp
  - wget http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.6.tar.gz
  - tar xvf libvorbis-*.tar.gz
  - cd libvorbis-*/
  - ./configure --target=i686-w64-mingw32   --host=i686-w64-mingw32 --build=i686-linux --prefix=/usr/i686-w64-mingw32
  - echo Compiling Vorbis for i686
  - make -j4
  - sudo make install
  - make distclean
  - ./configure --target=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --build=x86_64-linux --prefix=/usr/x86_64-w64-mingw32
  - echo Compiling Vorbis for x86_64
  - make -j4
  - sudo make install
  - popd

install:
  - echo Building UA_Source for Windows
  - cd src/
  - CXX=i686-w64-mingw32-g++ CC=i686-w64-mingw32-gcc make win32

before_script:
  - echo Nothing yet

script:
  - echo Nothing yet

after_script:
  - echo Nothing yet

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "goldstar611"
  - git config --local user.email "$EMAIL"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - zip -j $TRAVIS_BUILD_DIR/ua_source_windows.zip -xi $TRAVIS_BUILD_DIR/src/*.exe
  - cp /usr/i686-w64-mingw32/bin/soft_oal.dll $TRAVIS_BUILD_DIR/OpenAL32.dll
  - zip -j $TRAVIS_BUILD_DIR/ua_source_windows.zip -xi $TRAVIS_BUILD_DIR/OpenAL32.dll
  - zip -j $TRAVIS_BUILD_DIR/ua_source_windows.zip -xi /usr/i686-w64-mingw32/bin/SDL2.dll
  - zip -j $TRAVIS_BUILD_DIR/ua_source_windows.zip -xi /usr/i686-w64-mingw32/bin/SDL2_image.dll
  - zip -j $TRAVIS_BUILD_DIR/ua_source_windows.zip -xi /usr/i686-w64-mingw32/bin/SDL2_ttf.dll
  - zip -j $TRAVIS_BUILD_DIR/ua_source_windows.zip -xi /usr/i686-w64-mingw32/bin/SDL2_net.dll
  - zip -j $TRAVIS_BUILD_DIR/ua_source_windows.zip -xi /usr/i686-w64-mingw32/bin/libvorbisfile-3.dll
  - zip -j $TRAVIS_BUILD_DIR/ua_source_windows.zip -xi /usr/i686-w64-mingw32/bin/libvorbis-0.dll
  - zip -j $TRAVIS_BUILD_DIR/ua_source_windows.zip -xi /usr/i686-w64-mingw32/bin/libfreetype-6.dll
  - zip -j $TRAVIS_BUILD_DIR/ua_source_windows.zip -xi /usr/i686-w64-mingw32/bin/libogg-0.dll
  - zip -j $TRAVIS_BUILD_DIR/ua_source_windows.zip -xi /usr/i686-w64-mingw32/bin/zlib1.dll
  - zip -j $TRAVIS_BUILD_DIR/ua_source_windows.zip -xi /usr/i686-w64-mingw32/lib/libwinpthread-1.dll
  - zip -j $TRAVIS_BUILD_DIR/ua_source_windows.zip -xi /tmp/openal-soft-*-bin/alsoft-config/libgcc_s_sjlj-1.dll
  - zip -j $TRAVIS_BUILD_DIR/ua_source_windows.zip -xi /tmp/openal-soft-*-bin/alsoft-config/libstdc++-6.dll
deploy:
  provider: releases
  api_key:
    secure: p0IjrperAH1NnT3C1G56/+AvxA+b+JVPKfg9AC4S2Qqyqf8eGhYek7RLSBn+4k2c6ByYrYyMWLmPidLLHTrYfRKw2i80hes/zGGy4OJllt+Ce+6eGRcyzb9zjwwnvGMgQlqMAWQFbLnWAYADgQtO31pBLd3sC486GUItVN9zOIy124cqmLDji1gdEqAI3noVQIPh5ENhs6kgVsL7Zyq9PUfLi/dH5r6HoxF5ayLuYyUm3xs0FqpKZQqa6wzdRLGbQvuBPJ6BziHxluAMlZ1cQ5V1Q18x6FQXAErdCSWWkmNxBqXOn4cjKvRVI0wZJ/vlvqHI98CF2mI8WqpN+49npfH/pLYwynKp8jL3gLmOA28ONhQfC3uw0heuOYTN7K8Iq/k8QbZEAxtMyFqILQVCMXc5t6h30uj4LMBgdvZEQFICVA3tJTnr+INna7UIPmMa4KXC5fisEJxnIjn5t2EG+41y67ixNeIUowWqOMwBMEnpsYdqIHSf7Hlr9cU4qpU2Z6YJ0bhndoIXfFtW0ngMDYlD+B3RLLQSxs3cesjvsS8X/jIiSdMTvTzAdX3YGtdAfGwT7ARXJtL8gk8PdLUiFMPrUHRIerI/qc/xTqew8GaYeWBdwwqh1FTxii+0VW7aM+UChaqNZdiuLk0hxZKMW4zR93bM7hKxq1eyLSQdjuA=
  file_glob: false
  file: $TRAVIS_BUILD_DIR/ua_source_windows.zip
  skip_cleanup: true
  on:
    branch: master

